config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    passwords: 'members/passwords'
  }
  
  resources :members do
    resources :cart_items
    delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_all_item'
    resources :orders do
      resources :order_items
    end
    resources :shipping_addresses
  end
  put "/members/:id/hide" => "members#hide", as: 'member_hide'
  
  get 'withdrawal' => 'members#withdrawal'
  
  resources :items
  
  root 'homes#top'
  get '/about' => 'homes#about'
  get '/redirect' => 'homes#redirect'
  get '/contact-form' => 'homes#contact_form'
  
  namespace :admin do 
    resources :genres
    resources :order_items
    resources :orders
    resources :members
    resources :items
    get '/homes/top' => 'homes#top'
  end

  get 'search' => 'search#search'
  get '/members/:member_id/about' => 'orders#about', as: 'order_about' 
  post '/members/:member_id' => 'orders#create', as: 'order_create'
  get '/members/:member_id/completion' => 'orders#completion', as: 'member_order_completion' 
  get '/:genre_id/items' => 'items#genre', as: 'genre_item'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @method = params["search"]["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == "member"
      if method == 'perfect'
        Member.where(name_family: content)
      elsif method == 'forward'
        Member.where('name_family LIKE ?', content+'%')
      elsif method == 'backward'
        Member.where('name_family LIKE ?', '%'+content)
      else
        Member.where('name_family LIKE ?', '%'+content+'%')
      end
    else
      if method == 'perfect'
        Item.where(name: content)
      elsif method == 'forward'
        Item.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        Item.where('name LIKE ?', '%'+content)
      else
        Item.where('name LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="container">
  <div class="row">
    <h2><%= @content %>の検索結果</h2>
  </div>
</div>

<% if @model == "member" %>
      <div class="container col-xs-6 col-xs-offset-3">
        <div class="row">
          <table class="table col-xs-8">
            <thead>
              <tr>
                <td>会員ID</td>
                <td>氏名</td>
                <td>メールアドレス</td>
                <td>ステータス</td>
              </tr>
            </thead>
            <% @records.each do |member| %>
              <tbody>
                <tr>
                  <td><%= member.id %></td>
                  <td>
                    <%= link_to admin_member_path(member) do %>
                      <%= member.name_family %>
                      <%= member.name_first %>
                    <% end %>
                  </td>
                  <td><%= member.email %></td>
                  <% if member.is_withdrawal_flag == "t" %>
                      <td>有効</td>
                    <% else %>
                      <td>退会済</td>
                  <% end %>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>

  <% else %>

  <div class="container">
    <div class="row">
      <div class="items">
        <% @records.each do |item| %>
          <div class="item-box">
            <%= link_to admin_item_path(item) do %>
              <%= attachment_image_tag item, :image, format: "jpeg", width:"200", height:"120", fallback: "no_image.jpg" %>
            <% end %>
            <h5><%= link_to item.name, item_path(item) %></h5>
            <p><span>¥</span><%= item.price.to_s(:delimited) %>（税抜）</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
<% end %>