config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    passwords: 'members/passwords'
  }
  
  resources :members do
    resources :cart_items
    delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_all_item'
    resources :orders do
      resources :order_items
    end
    resources :shipping_addresses
  end
  put "/members/:id/hide" => "members#hide", as: 'member_hide'
  
  get 'withdrawal' => 'members#withdrawal'
  
  resources :items
  
  root 'homes#top'
  get '/about' => 'homes#about'
  get '/redirect' => 'homes#redirect'
  get '/contact-form' => 'homes#contact_form'
  
  namespace :admin do 
    resources :genres
    resources :order_items
    resources :orders
    resources :members
    resources :items
    get '/homes/top' => 'homes#top'
  end

  get 'search' => 'search#search'
  get '/members/:member_id/about' => 'orders#about', as: 'order_about' 
  post '/members/:member_id' => 'orders#create', as: 'order_create'
  get '/members/:member_id/completion' => 'orders#completion', as: 'member_order_completion' 
  get '/:genre_id/items' => 'items#genre', as: 'genre_item'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_items, dependent: :destroy

#中間テーブルを介して複数のプロダクトを持つ
  has_many :items, :through => :order_items

  enum payment_method: [:クレジットカード, :銀行振込]
  enum order_status: [ :入金待ち, :入金確認, :製作中, :発送準備中, :発送済み ]

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :receiver, presence: true
  validates :payment_method, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def edit
    @production_status = OrderItem.production_status.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
      if params[:order][:order_status] == "入金確認"
          @order_items.each do |order_item|
            order_item.production_status = "製作待ち"
            order_item.save(order_params)
          end
      end

    @order.update(order_params)
     flash[:success] = "注文ステータスを更新しました！"
    redirect_to request.referer
  end

  def index
    @orders = Order.page(params[:page]).reverse_order
    @order_items = OrderItem.all
    @total_quantity = 0
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total = 0
    @postage = 800
    @member = Member.order(params[:id])


end

  # private
  # def order_params
  #   params.require(:order).permit(:member_id, :order_status, :postal_code)
  # end
  private
  def order_params
    params.require(:order).permit(:member_id, :order_status, :postal_code,
     :receiver, :address, :postage, :payment_method, :total, :created_at, :updated_at,
     order_items_attributes: [:order_id, :item_id, :quantity, :tax_inculuded_price, :production_status],
     members_attributes: [:name_family, :name_first ])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :current_member?
  before_action :destroy_all, only: [:completion]
  @@button_selected = ""

  def index
    @member = Member.find(params[:member_id])
    @orders = @member.orders.page(params[:page]).reverse_order.per(5)
    @order_items = OrderItem.all
    @total = 0
    @postage = 800
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total = 0
    @postage = 800
    if @order.member_id != current_member.id
      redirect_back(fallback_location: root_path)
      flash[:alert] = "アクセスに失敗しました。"
    end
  end

  def new

    @order_new = Order.new
    @order = Order.new
    @member = Member.find(current_member.id)
    @member_shipping_addresses = @member.shipping_addresses

  end


  def confirm
  end

  def about
    @order = Order.new
    @order.order_items.build
    @total = 0
    @shipping_cost = 800
    @cart_items_member = CartItem.where(member_id: current_member.id)
    @member = Member.find(params[:member_id])
    @tax = 1.1

    @payment_method_enum = params[:payment_method]
    case @payment_method_enum
    when "0"
      @payment_method = "銀行振込"
    when "1"
      @payment_method = "クレジットカード"
    end

    @@button_selected = params[:selected]
    case @@button_selected
    when "a"
      @postal_code = params[:postal_code]
      @address = params[:address]
      @receiver = params[:name_family] + params[:name_first]
    when "b"
      if params[:shipping_address].blank?
        flash[:danger] = "お届け先が未入力です。"
        @member_shipping_addresses = @member.shipping_addresses
        render :new
      else
        shipping_address_id = params[:shipping_address]
        @postal_code = @member.shipping_addresses.find(shipping_address_id).postal_code
        @address = @member.shipping_addresses.find(shipping_address_id).address
        @receiver = @member.shipping_addresses.find(shipping_address_id).receiver
      end
    when "c"
      if params[:p].blank? || params[:a].blank? || params[:r].blank?
        flash[:danger] = "お届け先が未入力です。"
        @member_shipping_addresses = @member.shipping_addresses
        render :new
      else
        @postal_code = params[:p]
        @address = params[:a]
        @receiver = params[:r]
      end
    end
  end

  def create
    @order = Order.new(order_params)
    @order.member_id = current_member.id
    @cart_items_member = current_member.cart_items
    @tax = 1.1

    if @order.save
      @cart_items_member.each do |cart_item|
        @order_item = OrderItem.new
        @order_item.order_id = @order.id
        @order_item.item_id = cart_item.item.id
        @order_item.quantity = cart_item.quantity
        @order_item.tax_included_price = (cart_item.item.price * @tax).floor.to_s(:delimited)
        @order_item.production_status = 0

        @order_item.save
      end
      if @@button_selected == "c"
        @shipping_address = ShippingAddress.new
        @shipping_address.member_id = params[:member_id]
        @shipping_address.postal_code = @order.postal_code
        @shipping_address.address = @order.address
        @shipping_address.receiver = @order.receiver
        @shipping_address.save
      end

      redirect_to member_order_completion_path
    else
      @member = Member.find(current_member.id)
      @member_shipping_addresses = @member.shipping_addresses
      render :new
    end
  end

  def completion

  end

  private
  def order_params
    params.require(:order).permit(:order_status, :postal_code, :receiver, :address, :postage, :payment_method, :total)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <h1>注文ステータス編集画面</h1>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<!-- admin order index -->
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
      <h3>注文履歴一覧</h3>
    </div>
  </div>
      <br>
  <div class="row">
      <div class="col-xs-8 col-xs-offset-1">
        <table class="table">
          <thead>
            <tr class="active">
              <td class="col-xs-2">
                購入日時
              </td>
              <td class="col-xs-2">
                購入者
              </td>
              <td class="col-xs-2">
                注文個数
              </td>
              <td class="col-xs-2">注文ステータス</td>
            </tr>
          </thead>

          <tbody>
          	<% @orders.each do |order| %>
            <tr>
              <td class="col-xs-2">
                <%= link_to admin_order_path(order) do %>
                  <%= order.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                <% end %>
                </td>
              <td class="col-xs-2">
                <%= order.member.name_family %><%= order.member.name_first %>
              </td>
                         <!-- 総数を出す -->
              <%

                items = order.order_items.count
                for i in 1 .. items
                  quantity = order.order_items[i - 1].quantity
                  @total_quantity = @total_quantity + quantity
                end

                %>

              <td class="col-xs-2">
                <%= @total_quantity %>
              </td>
              <td class="col-xs-2">
                <%= order.order_status %>
              </td>
            </tr>
            <!-- 総数のクリア -->
              <% @total_quantity = 0 %>
            <% end %>
          </tbody>

        </table>
        <%= paginate @orders %>
      </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<!-- admin order show兼edit -->
<div class="container">
  <div class="row">
    <% if flash[:success] %>
      <div class="flash">
        <%= flash[:success] %>
      </div>
    <% end %>
    <div class="col-xs-3 col-xs-offset-1">
      <h4>注文履歴詳細</h4>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-8">
      <table>
        <tr>
          <th class="col-xs-2">購入者</th>
            <td class="col-xs-6">
              <%= link_to admin_member_path(@order.member_id) do %>
          	    <%= @order.member.name_family %><%= @order.member.name_first %>
          	  <% end %>
          	</td>
        </tr>
        <tr>
          <th class="col-xs-2">配送先</th>
          <td class="col-xs-6">
            <%= @order.postal_code %><%= @order.address %><br>
            <%= @order.receiver %>
          </td>
        </tr>
        <tr>
          <th class="col-xs-2">支払方法</th>
          <td class="col-xs-6"><%= @order.payment_method %></td>
        </tr>
         <tr>
           <th class="col-xs-2">注文ステータス</th>
           <td class="col-xs-6">
            <%= form_for @order, url: admin_order_path(@order), method: :patch do |f| %>
              <%= f.select :order_status, Order.order_statuses.keys.to_a %>
              <%= f.submit "更新", class:"btn btn-primary" %>
            <% end %>
            </td>
         </tr>

      </table>
    </div>
  </div>
  <br>
  <div class ="row">
    <div class="col-xs-8 ">

      <table class="table">
        <thead>
          <tr class="active">
           <td>商品名</td>
            <td>単価（税込）</td>
            <td>数量</td>
            <td>小計</td>
            <td>製作ステータス</td>
            <td></td>
          </tr>
        </thead>

        <% @order_items.each do |order_item| %>
        <tbody>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.tax_included_price %>円</td>
            <td><%= order_item.quantity %>個</td>
            <td><%= order_item.tax_included_price * order_item.quantity %>円</td>
                    <!-- 製作ステータス -->
            <td>
              <%= form_for (order_item), url: admin_order_item_path(order_item), method: :patch do |f| %>
              	<%= f.select :production_status, OrderItem.production_statuses.keys.to_a %>
                <%= f.hidden_field :order_id, value: order_item.order_id %>
              	<%= f.submit "更新", class:"btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% @total = @total + order_item.tax_included_price * order_item.quantity %>
        <% end %>
      </table>

    </div>
    <br>
    <div class="col-xs-4">
      <table>
        <tr>
          <th>商品合計</th><td><%= @total.floor.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th><td><%= @order.postage %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th><td><%= (@total + @order.postage).floor.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>