config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    passwords: 'members/passwords'
  }
  
  resources :members do
    resources :cart_items
    delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_all_item'
    resources :orders do
      resources :order_items
    end
    resources :shipping_addresses
  end
  put "/members/:id/hide" => "members#hide", as: 'member_hide'
  
  get 'withdrawal' => 'members#withdrawal'
  
  resources :items
  
  root 'homes#top'
  get '/about' => 'homes#about'
  get '/redirect' => 'homes#redirect'
  get '/contact-form' => 'homes#contact_form'
  
  namespace :admin do 
    resources :genres
    resources :order_items
    resources :orders
    resources :members
    resources :items
    get '/homes/top' => 'homes#top'
  end

  get 'search' => 'search#search'
  get '/members/:member_id/about' => 'orders#about', as: 'order_about' 
  post '/members/:member_id' => 'orders#create', as: 'order_create'
  get '/members/:member_id/completion' => 'orders#completion', as: 'member_order_completion' 
  get '/:genre_id/items' => 'items#genre', as: 'genre_item'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

# バリデーション
validates :email, presence: true
validates :name_family, presence: true
validates :name_first, presence: true
validates :name_first_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
validates :name_family_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}

# numericality => only_integerで整数のみ、
# ０以上１０未満のみ
# ハイフンなしの7桁
validates :postal_code, presence: true, format: {with: /\A\d{7}\z/},
numericality: { only_integer: true }

# 電話番号10桁（固定電話）or11桁（携帯電話）
VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
validates :phone_number, presence: true, format: { with: VALID_PHONE_REGEX },
numericality: {only_integer: true,}

  def active_for_authentication?
    super && (self.is_withdrawal_flag == "t" )
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @members = Member.page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_members_path
    else
      render :edit
    end
  end

private

def member_params
  params.require(:member).permit(
    :name_family, 
    :name_first, 
    :name_family_kana, 
    :name_first_kana,
    :postal_code,
    :address,
    :phone_number,
    :email,
    :is_withdrawal_flag
  )
end

end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  before_action :reject_member, only: [:create]

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_member
    @member = Member.find_by(email: params[:member][:email])
    if @member
      if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_member_session_path
      end
    else
      flash[:error] = "入力内容を再確認してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :authenticate_member!
  before_action :current_member?, except: :withdrawal

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
       redirect_to member_path(@member)
    else
       render :edit
    end
  end

  def withdrawal
  end

  def hide
    @member = Member.find(params[:id])
    @member.update(is_withdrawal_flag: false)
    reset_session
    redirect_to root_path
  end

  private

  def member_params
    params.require(:member).permit(
      :name_family,
      :name_first,
      :name_family_kana,
      :name_first_kana,
      :postal_code,
      :address,
      :phone_number,
      :email
    )
  end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<%# 顧客の登録情報編集ページ %>
<div class="container">
  <div class="row">
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2 style="color: red;"><%= @member.errors.count %>件のエラーが発生しました</h2>
      <ul style="color: red;">
        <% @member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <h2>登録情報編集</h2>
   <%= form_for(@member) do |f| %>
      <table class="table col-xs-7">
        <tbody>
          <tr>
            <td class="col-xs-2">氏名</td>
            <td class="col-xs-5">（姓）<%= f.text_field :name_family, autofocus: true %></td>
            <td>（名）<%= f.text_field :name_first, autofocus: true %></td>
          </tr>
          <tr>
            <td class="col-xs-2">カナ</td>
            <td>（セイ）<%= f.text_field :name_family_kana, autofocus: true %></td>
            <td>（メイ）<%= f.text_field :name_first_kana, autofocus: true %></td>
          </tr>
          <tr>
            <td class="col-xs-2">郵便番号</td>
            <td><%= f.text_field :postal_code, autofocus: true %></td>
          </tr>
          <tr>
            <td class="col-xs-2">住所</td>
            <td><%= f.text_field :address, autofocus: true %></td>
          </tr>
          <tr>
            <td class="col-xs-2">電話番号</td>
            <td><%= f.text_field :phone_number, autofocus: true %></td>
          </tr>
          <tr>
            <td class="col-xs-2">メールアドレス</td>
            <td><%= f.text_field :email, autofocus: true %></td>
          </tr>
          <tr>
            <td><%= f.submit '編集内容を保存する', class: "btn btn-primary"%></td>
            <td><%= link_to '退会する', withdrawal_path, class: "btn btn-danger" %></td>
          </tr>
        </tbody>
      </table>
    <% end %> 
  </div>
</div>

app/views/members/show.html.erb
<%# 顧客マイページ %>
<div class="container">
  <div class="row">
    <h3>マイページ</h3>
    <div class="my-page-sub-title">
      <span>登録情報</span>
      <%= link_to '編集する', edit_member_path(@member.id), class: "btn btn-primary" %>
      <%= link_to 'パスワードを変更する', edit_member_registration_path, class: "btn btn-primary" %>
    </div>
    <div class="member-info">
      <table class="table-bordered col-xs-6">
        <tbody>
          <tr>
            <td class="col-xs-3 sub-title-cell my-page-td">氏名</td>
            <td class="col-xs-6 my-page-td"><%= @member.name_family %><%= @member.name_first %></td>
          </tr>
          <tr>
          <td class="col-xs-3 sub-title-cell my-page-td">カナ</td>
          <td class="col-xs-6 my-page-td"><%= @member.name_family_kana %><%= @member.name_first_kana %></td>
          </tr>
          <tr>
          <td class="col-xs-3 sub-title-cell my-page-td">郵便番号</td>
          <td class="col-xs-6 my-page-td"><%= @member.postal_code %></td>
          </tr>
          <tr>
          <td class="col-xs-3 sub-title-cell my-page-td">住所</td>
          <td class="col-xs-6 my-page-td"><%= @member.address %></td>
          </tr>
          <tr>
          <td class="col-xs-3 sub-title-cell my-page-td">電話番号</td>
          <td class="col-xs-6 my-page-td"><%= @member.phone_number %></td>
          </tr>
          <tr>
          <td class="col-xs-3 sub-title-cell my-page-td">メールアドレス</td>
          <td class="col-xs-6 my-page-td"><%= @member.email %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="container order-info-button">
  <div class="row">
    <table class="table-borderless col-xs-6">
      <thead>
        <tr>
          <td class="col-xs-2 my-page-td"><h3>配送先</h3></td>
          <td class="col-xs-6 my-page-td"><%= link_to '一覧を見る',  member_shipping_addresses_path(@member.id), class: "btn btn-primary col-xs-4" %> </td>
        </tr>
        <tr>
        <td class="col-xs-2 my-page-td"><h3>注文履歴</h3></td>
        <td class="col-xs-6 my-page-td"><%= link_to '一覧を見る', member_orders_path(@member.id), class: "btn btn-primary col-xs-4" %></td>
        </tr>
      </thead>
    </table>
  </div>
</div>

app/views/members/withdrawal.html.erb
<%# 会員退会ページ %>

<div class="container withdrwal">
  <div class="row">
     <h2 class="withdrwal-title">本当に退会しますか？</h2>

      <div class="withdrwal-text">
        <p>
        退会すると、会員登録情報や<br>
        これまでの購入履歴が閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。
        </p>
      </div>

    <div class="withdrwal-button">
      <%= link_to '退会しない', member_path(current_member), class: "btn btn-primary" %>
      <%= link_to '退会する', member_hide_path(current_member), method: :put, class: "btn btn-danger" %>
    </div>

  </div>
</div>